#!/usr/bin/env python3
"""
One-time setup script to get YouTube OAuth credentials
Run this once to authenticate and save your refresh token
"""

import os
import json
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials

# YouTube API scopes
SCOPES = ['https://www.googleapis.com/auth/youtube.upload']

def setup_oauth():
    """
    Guide user through OAuth setup and save refresh token
    """
    print("\n" + "="*70)
    print("YouTube OAuth Setup")
    print("="*70)
    print("\nThis script will help you set up YouTube API credentials.\n")

    # Check if client_secrets.json exists
    if not os.path.exists('client_secrets.json'):
        print("❌ Error: client_secrets.json not found!")
        print("\nYou need to:")
        print("1. Go to https://console.cloud.google.com/")
        print("2. Create a new project (or select existing)")
        print("3. Enable YouTube Data API v3")
        print("4. Create OAuth 2.0 Client ID credentials")
        print("5. Download the JSON file")
        print("6. Save it as 'client_secrets.json' in this directory")
        print("\nDetailed instructions:")
        print("  a. In Google Cloud Console, go to 'APIs & Services' > 'Credentials'")
        print("  b. Click 'Create Credentials' > 'OAuth client ID'")
        print("  c. Choose 'Desktop app' as application type")
        print("  d. Download the JSON file")
        print("  e. Rename it to 'client_secrets.json'")
        return None

    print("✅ Found client_secrets.json\n")
    print("🔐 Starting OAuth flow...")
    print("   A browser window will open for you to authorize the app.\n")

    # Run OAuth flow
    flow = InstalledAppFlow.from_client_secrets_file(
        'client_secrets.json',
        SCOPES
    )

    # This will open a browser window
    creds = flow.run_local_server(port=8080)

    print("\n✅ Authentication successful!")

    # Create .env file with credentials
    env_content = f"""# YouTube API Credentials
# Generated by setup_youtube_oauth.py

YOUTUBE_CLIENT_ID={creds.client_id}
YOUTUBE_CLIENT_SECRET={creds.client_secret}
YOUTUBE_REFRESH_TOKEN={creds.refresh_token}
"""

    with open('.env', 'w') as f:
        f.write(env_content)

    print("\n✅ Credentials saved to .env file")
    print("\n" + "="*70)
    print("Setup complete!")
    print("="*70)
    print("\nYou can now use the YouTube uploader.")
    print("Your credentials are stored securely in .env\n")

    # Add .env to .gitignore if it exists
    gitignore_path = '.gitignore'
    if os.path.exists(gitignore_path):
        with open(gitignore_path, 'r') as f:
            gitignore_content = f.read()

        if '.env' not in gitignore_content:
            with open(gitignore_path, 'a') as f:
                f.write('\n.env\n')
            print("✅ Added .env to .gitignore\n")
    else:
        with open(gitignore_path, 'w') as f:
            f.write('.env\nclient_secrets.json\n')
        print("✅ Created .gitignore with .env and client_secrets.json\n")

    return creds


if __name__ == '__main__':
    setup_oauth()
